### ISSUE TITLE
1 getRoutes should be called before iterations

### ISSUE THREAD

**Issue by esteblock** [soroswap/soroswap-router-sdk#24]
Currently in `src/router/router`, `routeSplit()` and `router()` call a lot of times to `routeExactIn` or `routeExactOut`.
Each of these functions will call `_getAllRoutes`

_getAllRoutes should be called before the iterations

**Comment by MattPoblete** [comment]
Fixed on PR #26, tested with jest

**Comment by MattPoblete** [comment]
Remember to create an issue when merge to update the fontend calls

**Comment by esteblock** [comment]
Included in Frontend soroswap-router-sdk": "^1.2.13
https://github.com/soroswap/frontend/pull/533
