### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by esteblock** [soroswap/soroswap-router-sdk#4]
- Usar JSDoc
- Host in Github

**Comment by abstract829** [comment]
falta hostear en github (yo no puedo)

**Comment by esteblock** [comment]
![Screenshot from 2024-03-12 12-45-07](https://github.com/soroswap/soroswap-router-sdk/assets/2274485/613f358e-7374-4748-80a4-4112123c3c97)
@abstract829 can you check?
